//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLIESC_CONUNI_GR08.ServiceReference2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.IConversionUnidadesServicio")]
    public interface IConversionUnidadesServicio {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversionUnidadesServicio/PulgadasACentimetros", ReplyAction="http://tempuri.org/IConversionUnidadesServicio/PulgadasACentimetrosResponse")]
        double PulgadasACentimetros(double pulgadas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversionUnidadesServicio/PulgadasACentimetros", ReplyAction="http://tempuri.org/IConversionUnidadesServicio/PulgadasACentimetrosResponse")]
        System.Threading.Tasks.Task<double> PulgadasACentimetrosAsync(double pulgadas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversionUnidadesServicio/CentimetrosAPulgadas", ReplyAction="http://tempuri.org/IConversionUnidadesServicio/CentimetrosAPulgadasResponse")]
        double CentimetrosAPulgadas(double centimetros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversionUnidadesServicio/CentimetrosAPulgadas", ReplyAction="http://tempuri.org/IConversionUnidadesServicio/CentimetrosAPulgadasResponse")]
        System.Threading.Tasks.Task<double> CentimetrosAPulgadasAsync(double centimetros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversionUnidadesServicio/CelciusAKelvin", ReplyAction="http://tempuri.org/IConversionUnidadesServicio/CelciusAKelvinResponse")]
        double CelciusAKelvin(double celcius);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversionUnidadesServicio/CelciusAKelvin", ReplyAction="http://tempuri.org/IConversionUnidadesServicio/CelciusAKelvinResponse")]
        System.Threading.Tasks.Task<double> CelciusAKelvinAsync(double celcius);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversionUnidadesServicio/KelvinACelcius", ReplyAction="http://tempuri.org/IConversionUnidadesServicio/KelvinACelciusResponse")]
        double KelvinACelcius(double kelvin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversionUnidadesServicio/KelvinACelcius", ReplyAction="http://tempuri.org/IConversionUnidadesServicio/KelvinACelciusResponse")]
        System.Threading.Tasks.Task<double> KelvinACelciusAsync(double kelvin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversionUnidadesServicio/GramosAKilogramos", ReplyAction="http://tempuri.org/IConversionUnidadesServicio/GramosAKilogramosResponse")]
        double GramosAKilogramos(double gramos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversionUnidadesServicio/GramosAKilogramos", ReplyAction="http://tempuri.org/IConversionUnidadesServicio/GramosAKilogramosResponse")]
        System.Threading.Tasks.Task<double> GramosAKilogramosAsync(double gramos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversionUnidadesServicio/KilogramosAGramos", ReplyAction="http://tempuri.org/IConversionUnidadesServicio/KilogramosAGramosResponse")]
        double KilogramosAGramos(double kilogramos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversionUnidadesServicio/KilogramosAGramos", ReplyAction="http://tempuri.org/IConversionUnidadesServicio/KilogramosAGramosResponse")]
        System.Threading.Tasks.Task<double> KilogramosAGramosAsync(double kilogramos);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IConversionUnidadesServicioChannel : CLIESC_CONUNI_GR08.ServiceReference2.IConversionUnidadesServicio, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConversionUnidadesServicioClient : System.ServiceModel.ClientBase<CLIESC_CONUNI_GR08.ServiceReference2.IConversionUnidadesServicio>, CLIESC_CONUNI_GR08.ServiceReference2.IConversionUnidadesServicio {
        
        public ConversionUnidadesServicioClient() {
        }
        
        public ConversionUnidadesServicioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConversionUnidadesServicioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConversionUnidadesServicioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConversionUnidadesServicioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double PulgadasACentimetros(double pulgadas) {
            return base.Channel.PulgadasACentimetros(pulgadas);
        }
        
        public System.Threading.Tasks.Task<double> PulgadasACentimetrosAsync(double pulgadas) {
            return base.Channel.PulgadasACentimetrosAsync(pulgadas);
        }
        
        public double CentimetrosAPulgadas(double centimetros) {
            return base.Channel.CentimetrosAPulgadas(centimetros);
        }
        
        public System.Threading.Tasks.Task<double> CentimetrosAPulgadasAsync(double centimetros) {
            return base.Channel.CentimetrosAPulgadasAsync(centimetros);
        }
        
        public double CelciusAKelvin(double celcius) {
            return base.Channel.CelciusAKelvin(celcius);
        }
        
        public System.Threading.Tasks.Task<double> CelciusAKelvinAsync(double celcius) {
            return base.Channel.CelciusAKelvinAsync(celcius);
        }
        
        public double KelvinACelcius(double kelvin) {
            return base.Channel.KelvinACelcius(kelvin);
        }
        
        public System.Threading.Tasks.Task<double> KelvinACelciusAsync(double kelvin) {
            return base.Channel.KelvinACelciusAsync(kelvin);
        }
        
        public double GramosAKilogramos(double gramos) {
            return base.Channel.GramosAKilogramos(gramos);
        }
        
        public System.Threading.Tasks.Task<double> GramosAKilogramosAsync(double gramos) {
            return base.Channel.GramosAKilogramosAsync(gramos);
        }
        
        public double KilogramosAGramos(double kilogramos) {
            return base.Channel.KilogramosAGramos(kilogramos);
        }
        
        public System.Threading.Tasks.Task<double> KilogramosAGramosAsync(double kilogramos) {
            return base.Channel.KilogramosAGramosAsync(kilogramos);
        }
    }
}
